### ISSUE TITLE
signalk-js-client error when doing npm install

### ISSUE THREAD

**Issue by seabits-steve** [fabdrol/signalk-dashboard#1]
Not sure if I've got a bad npm version or something else...

`npm ERR! git clone git@github.com:github:signalk/signalk-js-client Cloning into bare repository '/home/pi/.npm/_git-remotes/git-github-com-github-signalk-signalk-js-client-460fa301'...
npm ERR! git clone git@github.com:github:signalk/signalk-js-client fatal: remote error: 
npm ERR! git clone git@github.com:github:signalk/signalk-js-client    is not a valid repository name
npm ERR! git clone git@github.com:github:signalk/signalk-js-client   Email support@github.com for help
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'signalk-client' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'volare-signalk-dashboard'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.1.19-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/volare-signalk-dashboard
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/volare-signalk-dashboard/npm-debug.log
npm ERR! not ok code 0
`

Running on a Raspberry Pi 3, Raspbian, already had SignalK running on it in a different dir...

Probably doing something stupid...

**Comment by fabdrol** [comment]
Not sure why it gives that error, but if I had to make a guess I'd say it's to do with the ancient versions of node and npm you are using ;-). You could try [this](http://andyfelong.com/2015/11/node-js-v4-1-0-on-raspberry-pi-2/) or any of the other guides on google. 

Let me know if it works!

**Comment by seabits-steve** [comment]
Ah boy I bet it installed node from the standard ubuntu side when I installed some of the dependencies for npm, and it's referencing that node version instead of the good one :)  Sorry.  That happens with SignalK sometimes too.

**Comment by fabdrol** [comment]
@stevepmitchell I'm closing this, assuming you got it to work. Should you still have issues, ping me on Slack.
